Repository ppc64le-cloud/pvsadm, pull requests merged in 2020-12, with the labels that each got.

#18 Use new cloud-init package
  cmd/image/qcow2ova/prep/prepare.go
  cmd/image/qcow2ova/prep/templates.go
Labels: approved, lgtm, size/S

#19 Changes for importing the image from S3 instance to PowerVS instance
  cmd/image/import/import.go
  pkg/client/image/image.go
  pkg/options.go
Labels: approved, lgtm, size/L

#20 Auto generate the service credential
  cmd/image/import/import.go
  cmd/root.go
  go.mod
  go.sum
  pkg/client/resource_controller2.go
  pkg/client/s3client.go
Labels: approved, lgtm, size/L

#21 Github action for releasing binaries
  .github/workflows/release.yml
Labels: approved, size/M

#22 Remove the stale code
  cmd/image/image.go
Labels: approved, lgtm, size/XS

#26 Add klog for setting log levels
  cmd/root.go
  go.mod
Labels: approved, lgtm, size/S

#30 Fix: Default region is not working for the image import command
  cmd/image/import/import.go
Labels: approved, lgtm, size/S

#35 Ship .tar.gz binary for each platform
  .github/workflows/release.yml
Labels: approved, kind/bug, lgtm, size/M

#39 Use external powervs utility to get the region
  go.mod
  go.sum
  pkg/client/pvmclient.go
  pkg/utils/region.go
  pkg/utils/region_test.go
Labels: approved, kind/bug, lgtm, priority/critical-urgent, size/L

#33 Hide debug flag
  cmd/root.go
Labels: approved, lgtm, priority/important-soon, size/XS

#42 Reuse the service credential
  cmd/image/import/import.go
  pkg/options.go
Labels: approved, lgtm, size/M

#45 Print the out and err to start standard out and err
  cmd/image/qcow2ova/prep/templates.go
  pkg/utils/cmd_exec.go
Labels: approved, kind/feature, lgtm, priority/important-soon, size/XS

#43 Fix: Verify s3 object exists or not
  cmd/image/import/import.go
  pkg/client/s3client.go
Labels: approved, lgtm, size/L

#50 Remove ibm repos
  cmd/image/qcow2ova/prep/templates.go
Labels: approved, kind/bug, lgtm, size/XS

#52 Fix: Consistent flag names across image upload and import sub-commands
  cmd/image/import/import.go
  cmd/image/qcow2ova/validate/register.go
  cmd/image/qcow2ova/validate/user/user.go
  cmd/image/upload/upload.go
Labels: approved, lgtm, size/M

#55 Remove ibm-repo properly
  cmd/image/qcow2ova/prep/templates.go
Labels: approved, lgtm, size/XS

#60 Print the usage for errors
  cmd/root.go
Labels: approved, lgtm, size/XS

#61 Hide audit-file option for image subcommand
  cmd/root.go
Labels: approved, lgtm, size/S

#63 Make template script configurable
  cmd/image/qcow2ova/prep/templates.go
  cmd/image/qcow2ova/qcow2ova.go
  pkg/options.go
Labels: approved, lgtm, size/M

#71 Generate the service credential per user
  cmd/image/import/import.go
Labels: approved, lgtm, size/S

#67 Add wait option for image import
  cmd/image/import/import.go
  go.mod
  go.sum
  pkg/options.go
Labels: approved, lgtm, size/L

#75 Select the default resource group for the account while creating the …
  cmd/image/upload/upload.go
  pkg/client/resource.go
Labels: approved, lgtm, size/S

#65 Fix:Enhance help messages for image upload and import commands
  cmd/image/import/import.go
  cmd/image/upload/upload.go
Labels: approved, lgtm, size/M

#80 purge vms will continue to GET others though get of a VM fails
  cmd/purge/vms/vms.go
Labels: approved, lgtm, size/XS

#81 Add image-name check
  cmd/image/qcow2ova/validate/image-name/image-name.go
  cmd/image/qcow2ova/validate/register.go
Labels: approved, lgtm, size/S

#83 Fix the import regression issues
  cmd/image/import/import.go
Labels: approved, lgtm, size/XS

#85 Generate the service credential by COS
  cmd/image/import/import.go
  go.sum
  pkg/client/resource_controller2.go
Labels: approved, lgtm, size/S

#89 Fix the ds-identify file
  cmd/image/qcow2ova/prep/prepare.go
  cmd/image/qcow2ova/prep/templates.go
Labels: approved, lgtm, size/S

#90 Disable the AT repo
  cmd/image/qcow2ova/prep/templates.go
Labels: approved, lgtm, size/XS

#95 Add windows support
  .github/workflows/go.yml
  .github/workflows/release.yml
  cmd/image/qcow2ova/prep/chroot.go
  cmd/image/qcow2ova/prep/chroot_windows.go
  cmd/image/qcow2ova/validate/diskspace/diskspace.go
  cmd/image/qcow2ova/validate/diskspace/diskspace_windows.go
Labels: approved, lgtm, size/M

#96 readme doc update for pvsadm.
  README.md
Labels: approved, lgtm, size/M

#99 Create get.sh
  get.sh
Labels: approved, lgtm, size/M

#100 Enhance get.sh script to work with curl command
  get.sh
Labels: approved, lgtm, size/M

#102 Issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, lgtm, size/M

#106 Add docs for image management
  README.md
  docs/Advanced Scenarios for Qcow2 to OVA.md
  docs/CentOS Qcow2 to OVA.md
  docs/RHCOS Qcow2 to OVA.md
  docs/RHEL Qcow2 to OVA.md
Labels: approved, kind/documentation, lgtm, size/M
