Repository ppc64le-cloud/pvsadm, pull requests merged in 2021-03, with the labels that each got.

#124 Enhancements for creation and deletion of the resource instances
  cmd/image/upload/upload.go
  pkg/client/client.go
  pkg/client/pvmclient.go
  pkg/client/resource.go
  pkg/client/s3client.go
Labels: approved, lgtm, size/L

#116 Script to upload images to PowerVS service
  samples/README.md
  samples/convert-upload-images-powervs/README.md
  samples/convert-upload-images-powervs/convert-upload-images-powervs
  samples/image-create-and-upload-sample/README.md
Labels: approved, lgtm, size/XL

#126 Add support for IBM Cloud test environment
  cmd/get/events/events.go
  cmd/image/import/import.go
  cmd/image/upload/upload.go
  cmd/purge/images/images.go
  cmd/purge/networks/networks.go
  cmd/purge/purge.go
  cmd/purge/vms/vms.go
  cmd/purge/volumes/volumes.go
  cmd/root.go
  pkg/client/client.go
  pkg/client/environments.go
  pkg/client/environments_test.go
  pkg/client/pvmclient.go
  pkg/options.go
  test/e2e/e2e_test.go
  test/e2e/rootcmd/environment.go
  test/e2e/rootcmd/framework.go
Labels: approved, lgtm, size/L

#127 README.md for convert-upload-images-powervs script
  samples/convert-upload-images-powervs/README.md
Labels: approved, lgtm, size/S

#128 Fixed broken download link and also fixed usage
  samples/convert-upload-images-powervs/README.md
Labels: approved, lgtm, size/XS

#129 Updated help function
  samples/convert-upload-images-powervs/convert-upload-images-powervs
Labels: approved, lgtm, size/S

#132 Update the cloud-init
  cmd/image/qcow2ova/prep/templates.go
Labels: approved, lgtm, size/L

#133 Bumped up pvsadm version
  samples/convert-upload-images-powervs/convert-upload-images-powervs
Labels: approved, lgtm, size/XS
