Repository ppc64le-cloud/pvsadm, pull requests merged in 2021-05, with the labels that each got.

#141 Add option to specify targetdisksize for OVA image
  cmd/image/qcow2ova/ova/ova.go
  cmd/image/qcow2ova/ova/template.go
  cmd/image/qcow2ova/qcow2ova.go
  pkg/options.go
Labels: lgtm, size/S

#143 Adding explicit steps for growing partitions
  cmd/image/qcow2ova/prep/templates.go
  cmd/image/qcow2ova/qcow2ova.go
Labels: lgtm, size/S

#144 Fixing indentation
  cmd/image/qcow2ova/prep/templates.go
Labels: approved, lgtm, size/XS

#146 Fixing the template and increasing the default image size
  cmd/image/qcow2ova/prep/templates.go
  cmd/image/qcow2ova/qcow2ova.go
Labels: approved, lgtm, size/XS

#145 dhcp-sync: sync dhcp config with powervs network
  cmd/dhcp-sync/dhcp-sync.go
  cmd/root.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L
