Repository ppc64le-cloud/pvsadm, pull requests merged in 2021-01, with the labels that each got.

#111 update go mod
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#109 Adding sample script for image create and upload
  README.md
  samples/README.md
  samples/image-create-and-upload-sample/config.sh
  samples/image-create-and-upload-sample/image_create_and_upload_script.sh
Labels: approved, lgtm, size/M

#112 Test framework
  .github/workflows/go.yml
  Makefile
  go.mod
  go.sum
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/framework.go
  test/e2e/qcow2ova/framework.go
  test/e2e/qcow2ova/qcow2ova.go
Labels: approved, lgtm, size/L

#114 Check platform first
  cmd/image/qcow2ova/validate/platform/platform.go
  cmd/image/qcow2ova/validate/register.go
Labels: approved

#107 Add Docs for Image upload and import commands
  README.md
  docs/How to Import Image to PowerVS Instance.md
  docs/How to Upload Image to COS.md
Labels: approved, lgtm, size/L
