Repository ppc64le-cloud/pvsadm, pull requests merged in 2021-02, with the labels that each got.

#79 Fix: prevent existing image overwrite in IBM cloud object store
  cmd/image/upload/upload.go
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/s3client.go
  pkg/client/s3utils/utils.go
  pkg/options.go
  pkg/utils/select.go
Labels: approved, lgtm, size/L

#119 Disable the network after firstboot
  cmd/image/qcow2ova/prep/templates.go
Labels: approved, lgtm, size/S

#121 Add optional cos-instance-name parameter for image import
  cmd/image/import/import.go
  pkg/client/s3client.go
  pkg/options.go
Labels: approved, lgtm, ok-to-test, size/XS
