Repository ppc64le-cloud/pvsadm, pull requests merged in 2022-08, with the labels that each got.

#314 Added support for upload with access and secretkey
  cmd/image/upload/upload.go
  docs/How to Upload Image to COS.md
  pkg/client/s3client.go
Labels: approved, size/M, lgtm, tide/merge-method-squash

#319 Added progress details while uploading the image to COS bucket
  pkg/client/s3client.go
Labels: approved, size/M, lgtm

#328 Fix verify
  cmd/image/sync/mock/sync_client_generated.go
  cmd/image/sync/sync_client.go
  cmd/image/sync/sync_test.go
  cmd/image/upload/upload.go
  hack/copyright_file
  pkg/client/environments.go
  pkg/client/environments_test.go
  pkg/utils/select.go
  pkg/utils/sync_test_utils.go
  test/e2e/rootcmd/environment.go
  test/e2e/rootcmd/framework.go
Labels: approved, size/L, lgtm

#326 Add dhcpserver command
  cmd/dhcpserver/cmd.go
  cmd/dhcpserver/create.go
  cmd/dhcpserver/delete.go
  cmd/dhcpserver/get.go
  cmd/dhcpserver/list.go
  cmd/root.go
  pkg/client/dhcp/dhcp.go
  pkg/client/pvmclient.go
Labels: approved, size/L, lgtm, tide/merge-method-squash
