Repository ppc64le-cloud/pvsadm, pull requests merged in 2022-01, with the labels that each got.

#221 updated the power-go-client library and api's
  cmd/create/port/port.go
  cmd/delete/port/port.go
  cmd/dhcp-sync/dhcp-sync.go
  cmd/get/ports/ports.go
  go.mod
  go.sum
  pkg/client/image/image.go
  pkg/client/instance/instance.go
  pkg/client/network/network.go
  pkg/client/pvmclient.go
  pkg/client/volume/volume.go
Labels: approved, size/L, lgtm

#224 Correct the script to point to latest code
  samples/convert-upload-images-powervs/convert-upload-images-powervs
Labels: size/S, lgtm

#225 Upgrading github.com/IBM-Cloud/power-go-client from 1.0.88 to 1.1.0
  cmd/purge/vms/vms.go
  go.mod
  go.sum
  pkg/client/events/events.go
  pkg/client/image/image.go
  pkg/client/network/network.go
  pkg/client/pvmclient.go
  pkg/client/volume/volume.go
Labels: approved, size/M, needs-ok-to-test, lgtm

#192 Added changes for deletion of sshKey/sshKeys
  cmd/purge/keys/keys.go
  cmd/purge/purge.go
  pkg/client/key/key.go
  pkg/client/pvmclient.go
  pkg/utils/select.go
Labels: approved, size/L, lgtm
