Repository ppc64le-cloud/pvsadm, pull requests merged in 2023-01, with the labels that each got.

#379 Image upload in staging/test env fix
  cmd/image/upload/upload.go
Labels: approved, lgtm, size/XS

#364 Updated unmount function with error handlers
  cmd/image/qcow2ova/prep/loop.go
  cmd/image/qcow2ova/qcow2ova.go
Labels: approved, size/S, lgtm, tide/merge-method-squash

#384 updated go version 1.19
  .github/workflows/go.yml
  .github/workflows/release.yml
  cmd/image/import/import.go
  cmd/image/qcow2ova/prep/prepare.go
  go.mod
  pkg/client/client.go
  pkg/client/image/image.go
  pkg/client/s3client.go
Labels: approved, size/M, lgtm, tide/merge-method-squash

#386 Supress NodeJS warnings in GitHub Actions.
  .github/dependabot.yml
  .github/workflows/go.yml
Labels: approved, lgtm, size/XS
