Repository ppc64le-cloud/pvsadm, pull requests merged in 2024-05, with the labels that each got.

#610 Add bucket exists check before checking object exists while uploading image
  cmd/image/upload/upload.go
Labels: approved, size/S, lgtm

#617 Remove k8s.io/apimachinery dependency for wait mechanism
  cmd/image/import/import.go
  go.mod
  go.sum
  pkg/utils/utils.go
Labels: approved, size/M, lgtm

#589 Renaming instance-id and instance-name
  README.md
  cmd/create/create.go
  cmd/create/port/port.go
  cmd/delete/delete.go
  cmd/delete/port/port.go
  cmd/dhcp-sync/dhcp-sync.go
  cmd/dhcpserver/cmd.go
  cmd/dhcpserver/create.go
  cmd/dhcpserver/delete.go
  cmd/dhcpserver/get.go
  cmd/dhcpserver/list.go
  cmd/get/events/events.go
  cmd/get/get.go
  cmd/get/peravailability/peravailability.go
  cmd/get/ports/ports.go
  cmd/image/import/import.go
  cmd/image/sync/mock/sync_client_generated.go
  cmd/image/upload/upload.go
  cmd/purge/images/images.go
  cmd/purge/keys/keys.go
  cmd/purge/networks/networks.go
  cmd/purge/purge.go
  cmd/purge/vms/vms.go
  cmd/purge/volumes/volumes.go
  docs/How to Import Image to PowerVS Instance.md
  pkg/options.go
  samples/convert-upload-images-powervs/convert-upload-images-powervs
  samples/image-create-and-upload-sample/README.md
  samples/image-create-and-upload-sample/config.sh
  samples/image-create-and-upload-sample/image_create_and_upload_script.sh
Labels: approved, size/L, lgtm
