Repository ppc64le-cloud/pvsadm, pull requests merged in 2024-01, with the labels that each got.

#537 Move to uber go-mock and bump go version to 1.21 across project.
  .github/workflows/codeql-analysis.yml
  .github/workflows/go.yml
  .github/workflows/release.yml
  cmd/image/sync/mock/sync_client_generated.go
  cmd/image/sync/sync_test.go
  go.mod
  go.sum
Labels: approved, size/M, lgtm

#538 Use alternate package for ioutil
  cmd/dhcp-sync/dhcp-sync.go
  cmd/image/info/info.go
  cmd/image/qcow2ova/get-image_test.go
  cmd/image/qcow2ova/prep/prepare.go
  cmd/image/qcow2ova/qcow2ova.go
  cmd/image/sync/sync.go
  cmd/image/sync/sync_test.go
  test/e2e/qcow2ova/qcow2ova.go
  test/e2e/sync/sync.go
Labels: approved, size/M, lgtm

#540 Fix cleanup of spec-files post e2e tests
  test/e2e/sync/sync.go
Labels: approved, lgtm, size/XS

#544 Give a meaningful name to the raw disk image.
  cmd/image/qcow2ova/ova/ova.go
  cmd/image/qcow2ova/qcow2ova.go
Labels: approved, size/S, lgtm
