Repository ppc64le-cloud/pvsadm, pull requests merged in 2024-11, with the labels that each got.

#687 Automates brew formula version bump for new release
  .github/workflows/release.yml
  ci/brew_formula_updater.sh
Labels: approved, size/L, lgtm

#680 Integrate a spinner to track time taken for long running operations #679
  cmd/image/import/import.go
  go.mod
  go.sum
  pkg/utils/utils.go
Labels: approved, size/M, lgtm, ok-to-test

#699 Introduces Github workflow to update homebrew formula in pvsadm tap repository on release
  .github/workflows/release.yml
  .github/workflows/update-homebrew-formula.yml
Labels: approved, size/M, lgtm

#700 Adds Github workflow to update homebrew formula in pvsadm tap repository
  .github/workflows/update-homebrew-formula.yml
Labels: approved, lgtm, size/XS

#701 Adds Github workflow to update homebrew formula in pvsadm tap repository
  .github/workflows/update-homebrew-formula.yml
Labels: approved, size/S, lgtm
