Repository ppc64le-cloud/pvsadm, pull requests merged in 2024-09, with the labels that each got.

#612 Deprecate bluemix-go and clean-up code.
  cmd/dhcp-sync/dhcp-sync.go
  cmd/dhcpserver/cmd.go
  cmd/get/cloudconnections/cloudconnections.go
  cmd/image/import/import.go
  cmd/image/sync/sync.go
  cmd/image/upload/upload.go
  cmd/purge/images/images.go
  cmd/purge/networks/networks.go
  cmd/purge/vms/vms.go
  cmd/purge/volumes/volumes.go
  cmd/root.go
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/environments.go
  pkg/client/pvmclient.go
  pkg/client/s3client.go
  pkg/utils/constants.go
  pkg/utils/utils.go
  test/e2e/sync/sync.go
Labels: approved, size/XXL, lgtm

#658 Fix the import package name for go-sdk-core
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/pvmclient.go
Labels: approved, size/S, lgtm

#660 Fix CLI operations that involve workspace-name
  pkg/client/pvmclient.go
Labels: approved, size/S, lgtm

#659 Code cleanup
  cmd/get/events/events.go
  cmd/get/peravailability/peravailability.go
  cmd/get/ports/ports.go
  cmd/image/import/import.go
  cmd/image/qcow2ova/ova/ova.go
  cmd/image/qcow2ova/password-generator.go
  cmd/image/qcow2ova/prep/chroot.go
  cmd/image/qcow2ova/qcow2ova.go
  cmd/image/qcow2ova/validate/diskspace/diskspace.go
  cmd/image/sync/sync.go
  cmd/image/sync/sync_test.go
  cmd/image/upload/upload.go
  cmd/purge/images/images.go
  cmd/purge/keys/keys.go
  cmd/purge/networks/networks.go
  cmd/purge/purge.go
  cmd/purge/vms/vms.go
  cmd/purge/volumes/volumes.go
  pkg/client/image/image.go
  pkg/client/network/network.go
  pkg/client/resource_controller2.go
  pkg/client/s3client.go
  pkg/client/volume/volume.go
  pkg/utils/constants.go
  pkg/utils/utils.go
  test/e2e/sync/sync.go
Labels: approved, size/L, lgtm

#662 Support port creation through workspace name
  cmd/create/create.go
  cmd/create/port/port.go
Labels: approved, lgtm, size/XS

#669 Fix broken version command.
  .github/ISSUE_TEMPLATE/bug_report.md
  cmd/create/port/port.go
  cmd/get/events/events.go
  cmd/get/peravailability/peravailability.go
  cmd/get/ports/ports.go
  cmd/image/import/import.go
  cmd/purge/purge.go
  cmd/root.go
  cmd/version/version.go
  get.sh
  pkg/utils/utils.go
Labels: approved, size/M, lgtm

#674 Fix get.sh to select between --version and version subcommand
  get.sh
Labels: approved, size/S, lgtm

#673 fix wrong duration showed for image import
  cmd/image/import/import.go
  cmd/image/sync/sync.go
  pkg/client/s3client.go
Labels: approved, size/S, lgtm, ok-to-test

#677 Align Tier info in help message
  cmd/image/import/import.go
Labels: approved, size/S, lgtm

#671 Refactor IBMCLOUD_API_KEY references
  cmd/image/import/import.go
  cmd/image/sync/sync.go
  cmd/image/upload/upload.go
  cmd/purge/purge.go
  cmd/root.go
  docs/How to Import Image to PowerVS Instance.md
  docs/How to Upload Image to COS.md
  pkg/client/s3client.go
  samples/convert-upload-images-powervs/convert-upload-images-powervs
  samples/image-create-and-upload-sample/image_create_and_upload_script.sh
  test/e2e/qcow2ova/qcow2ova.go
  test/e2e/sync/sync.go
Labels: approved, size/M, lgtm, ok-to-test
