Repository ppc64le-cloud/pvsadm, pull requests merged in 2024-04, with the labels that each got.

#440 Updating template for conversion of qcow2ova image
  cmd/image/qcow2ova/prep/templates.go
Labels: approved, lgtm, size/XS

#594 Free up loopdevice after image is built
  cmd/image/qcow2ova/prep/loop.go
  cmd/image/qcow2ova/prep/prepare.go
Labels: approved, size/S, lgtm

#592 Beautify output for dhcpserver commands
  cmd/dhcpserver/get.go
  cmd/dhcpserver/list.go
Labels: approved, size/M, lgtm

#506 Added log levels
  cmd/create/port/port.go
  cmd/delete/port/port.go
  cmd/dhcp-sync/dhcp-sync.go
  cmd/dhcpserver/create.go
  cmd/dhcpserver/delete.go
  cmd/dhcpserver/get.go
  cmd/dhcpserver/list.go
  cmd/get/events/events.go
  cmd/get/peravailability/peravailability.go
  cmd/get/ports/ports.go
  cmd/image/import/import.go
  cmd/image/info/info.go
  cmd/image/qcow2ova/get-image.go
  cmd/image/qcow2ova/prep/loop.go
  cmd/image/qcow2ova/prep/prepare.go
  cmd/image/qcow2ova/qcow2ova.go
  cmd/image/qcow2ova/validate/diskspace/diskspace_windows.go
  cmd/image/qcow2ova/validate/tools/tools.go
  cmd/image/qcow2ova/validate/validate.go
  cmd/image/sync/sync.go
  cmd/image/sync/sync_test.go
  cmd/image/upload/upload.go
  cmd/purge/images/images.go
  cmd/purge/keys/keys.go
  cmd/purge/networks/networks.go
  cmd/purge/vms/vms.go
  cmd/purge/volumes/volumes.go
  cmd/root.go
  pkg/audit/audit.go
  pkg/client/client.go
  pkg/client/network/network.go
  pkg/client/pvmclient.go
  pkg/client/s3client.go
  pkg/client/volume/volume.go
  pkg/utils/select.go
  test/e2e/sync/sync.go
Labels: approved, size/L, lgtm

#601 Minor fix on dhcp server get id flag description
  cmd/dhcpserver/get.go
Labels: approved, lgtm, size/XS

#602 Add doc to build centos image with DHCP support
  README.md
  docs/Build DHCP enabled Centos Images.md
Labels: approved, size/M, lgtm
